# Day 1 — EDA, Cleaning, and Sentiment Labels

## Today’s Goal

Understand the dataset before training any machine learning model.

By the end of today, we should know:

- what each important column represents
- which data is missing
- whether there are duplicate reviews
- how star ratings are distributed
- how to create sentiment labels
- whether the sentiment classes are balanced
- which cleaning decisions we will use later for model training

---

## Roadmap

### 1. Load the dataset
- import Pandas
- load `1429_1.csv`
- inspect the first rows

### 2. Understand the dataset
- number of rows and columns
- column names
- identify review text, rating, product name, and category fields

### 3. Investigate missing values
- count missing values
- identify which missing values matter for sentiment analysis
- create a sentiment-specific DataFrame

### 4. Investigate duplicates
- check repeated review text
- inspect examples
- decide whether duplicates should be removed

### 5. Inspect ratings
- count 1, 2, 3, 4, and 5-star reviews
- understand whether ratings are balanced

### 6. Create sentiment labels
- 1–2 stars → Negative
- 3 stars → Neutral
- 4–5 stars → Positive

### 7. Check class balance
- count Negative / Neutral / Positive
- identify whether one class dominates

### 8. Document cleaning decisions
Write down:
- what we removed
- what we kept
- why
- possible risks or limitations

# Day 1 — EDA and Data Cleaning

## Goal

Understand the structure and quality of the Amazon product reviews dataset before training any machine learning model.

We will inspect:
- the dataset structure
- the important columns
- missing values
- duplicate reviews
- star ratings
- sentiment labels
- class balance

## 1. Loading the dataset

We will use Pandas to work with the CSV file.

Pandas is a Python library for working with structured, table-like data.

When Pandas loads a CSV file, it creates a DataFrame.

A DataFrame is similar to a spreadsheet table:
- rows represent records
- columns represent variables or fields

In [1]:
import pandas as pd

## 2. Loading the CSV file

The dataset is stored inside the `datasets` folder.

We will use `pd.read_csv()` to load the CSV into a Pandas DataFrame.

Because this notebook is inside the `notebooks` folder, we need to go one level up (`..`) and then enter the `datasets` folder.

In [2]:
df = pd.read_csv("../datasets/1429_1.csv")

/var/folders/1g/3xm4lnvn64z02xj5s9vlj7hc0000gn/T/ipykernel_9680/2983328222.py:1: DtypeWarning: Columns (0: name, 1: reviews.didPurchase) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../datasets/1429_1.csv")

In [3]:
df.head()

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [ ]:
## 3. Understanding the dataset structure

Before cleaning anything, we want to understand:

- how many rows and columns exist
- what the column names are
- what one row represents

In [4]:
df.shape

(34660, 21)

In [6]:
df.columns

Index(['id', 'name', 'asins', 'brand', 'categories', 'keys', 'manufacturer',
       'reviews.date', 'reviews.dateAdded', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.userCity',
       'reviews.userProvince', 'reviews.username'],
      dtype='str')

## 4. Missing values

Real-world datasets are often incomplete.

Pandas represents many missing values as `NaN`.

Before removing anything, we first need to understand:
- which columns have missing values
- how many values are missing
- whether those columns matter for our project

In [7]:
# Count the number of missing values in each column.
df.isna().sum()

id                          0
name                     6760
asins                       2
brand                       0
categories                  0
keys                        0
manufacturer                0
reviews.date               39
reviews.dateAdded       10621
reviews.dateSeen            0
reviews.didPurchase     34659
reviews.doRecommend       594
reviews.id              34659
reviews.numHelpful        529
reviews.rating             33
reviews.sourceURLs          0
reviews.text                1
reviews.title               6
reviews.userCity        34660
reviews.userProvince    34660
reviews.username            7
dtype: int64

Which missing values prevent us from completing our tasks?

reviews.text
reviews.rating

review text
    ↓
model input

rating
    ↓
sentiment label

## 5. Inspecting missing critical values

Not every missing value is equally important.

Sentiment analysis = using a model to classify the feeling/opinion in a text, for example positive, neutral, or negative.

For sentiment analysis, the two essential fields are:

- `reviews.text`
- `reviews.rating`

Before removing rows, we will inspect the records where these values are missing.

In [8]:
# Show rows where the review text is missing.
df[df["reviews.text"].isna()]

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
3111,AVsRjfwAU2_QcyX9PHqe,Amazon 5W USB Official OEM Charger and Power A...,B01J2G4VBG,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...","0841667120171,841667120171,amazon5wusbofficial...",Amazon,2017-04-17T00:00:00.000Z,NaN,2017-12-30T00:00:00Z,...,NaN,NaN,NaN,5.0,https://www.amazon.com/product-reviews/B01J2G4...,NaN,Five Stars,NaN,NaN,lawrence s martin

In [9]:
df[df["reviews.rating"].isna()]

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
2886,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-12-14T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,The Kindle is my first e-ink reader. I own an ...,"Worth the money. Not perfect, but very very go...",NaN,NaN,Jeffrey Stanley
2887,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-10-19T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,"I'm a first-time Kindle owner, so I have nothi...","I Wanted a Dedicated E-Reader, and That's What...",NaN,NaN,Matthew Coenen
2888,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-12-08T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,UPDATE NOVEMBER 2011:My review is now over a y...,Kindle vs. Nook (updated),NaN,NaN,Ron Cronovich
2889,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-11-30T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,"I'm a first-time Kindle owner, so I have nothi...","I Wanted a Dedicated E-Reader, and That's What...",NaN,NaN,Matthew Coenen
2890,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-10-09T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I woke up to a nice surprise this morning: a n...,"Not the perfect do-it-all device, but very clo...",NaN,NaN,C. Tipton
2891,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-09-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,The Kindle is my first e-ink reader. I own an ...,"Worth the money. Not perfect, but very very go...",NaN,NaN,Jeffrey Stanley
2892,AVpfBEWcilAPnD_xTGb7,"Kindle Keyboard,,,\r\nKindle Keyboard,,,",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-09-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,UPDATE NOVEMBER 2011:br /br /My review is now ...,Kindle vs. Nook (updated),NaN,NaN,Ron Cronovich
2893,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,NaN,NaN,2015-09-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I woke up to a nice surprise this morning: a n...,"Not the perfect do-it-all device, but very clo...",NaN,NaN,C. Tipton
2894,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-05T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I use to hate to read but now that I have my K...,Great,NaN,NaN,D. Tatro
2895,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-03T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,All of them quit working. There's absolutely n...,I've had 3!,NaN,NaN,M. Lansford Kindle fave
2896,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-04T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I recently ordered my 8th Kindle. It was to re...,Kindle Customer Service vs. Comcast,NaN,NaN,Jean F. Bryant Wordwright
2897,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-05T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,Great. Love it.,I love it,NaN,NaN,Jeff Maddox
2898,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2010-09-02T05:00:00Z,NaN,2015-01-12T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I researched the purchase of a Kindle for a lo...,A hesistant buyer rejoices on his choice,NaN,NaN,Mr Goodwrench
2899,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-02T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,This thing has captured my wife's heart. She r...,Ruined my marriage,NaN,NaN,ken
2900,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-06T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I got my Kindle a few years ago and barely use...,Not a long-lasting product!,NaN,NaN,Lucky Luke
2901,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-06T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,It was excellent for me in one moment when I w...,Good device,NaN,NaN,George
2902,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-06T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,Bought for my husband for Christmas and I have...,Great,NaN,NaN,Kelly Beaumont
2903,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-06T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,It simply works even after 3.5 years of consta...,Do I need to say anything more?,NaN,NaN,Alexandr Petak
2904,AVpfBEWcilAPnD_xTGb7,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B002Y27P3M,Amazon,"Kindle Store,Amazon Devices,Electronics","kindlekeyboard/b002y27p3m,amazon/d01101",Amazon,2014-05-07T05:00:00Z,NaN,2015-01-17T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Wireless-Reader-W...,I would highly recommend them to everyone. Got...,Great Service,NaN,NaN,Di
3691,AVpfwS_CLJeJML43DH5w,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B0083Q04TA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","amazon/53000386,amazonkindlefirehd3rdgeneratio...",Amazon,2012-09-14T00:00:00Z,NaN,2015-11-04T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Display-Wi-Fi-Pre...,UPDATE: I bought both a Fire HD and a Gen 2. (...,Compare FIRE HD to the KINDLE FIRE GEN 2,NaN,NaN,clickz4
3692,AVpfwS_CLJeJML43DH5w,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B0083Q04TA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","amazon/53000386,amazonkindlefirehd3rdgeneratio...",Amazon,2012-09-21T00:00:00Z,NaN,2015-11-04T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Display-Wi-Fi-Pre...,I just received my kindle fire today. I had a ...,Best value,NaN,NaN,Me
3693,AVpfwS_CLJeJML43DH5w,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B0083Q04TA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","amazon/53000386,amazonkindlefirehd3rdgeneratio...",Amazon,2012-10-01T00:00:00Z,NaN,2015-11-04T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Display-Wi-Fi-Pre...,I purchased the Kindle Fire ten months ago for...,Wonderful product and incredible support from ...,NaN,NaN,Lisa
3694,AVpfwS_CLJeJML43DH5w,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B0083Q04TA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","amazon/53000386,amazonkindlefirehd3rdgeneratio...",Amazon,2012-09-17T00:00:00Z,NaN,2015-11-04T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Display-Wi-Fi-Pre...,"My 7 year old son has the 1st gen Kindle Fire,...",Great product but they get you with the ads an...,NaN,NaN,Old School Working Mom
14727,AVpff7_VilAPnD_xc1E_,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B00DU15MU4,Amazon,"Electronics,Categories,Streaming Media Players...","848719035551,0848719035551,certifiedrefurbishe...",Amazon,2014-04-03T00:00:00Z,NaN,2015-10-16T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Certified-Refurbished-Am...,"Having received my Fire TV today, I've been tr...",Works great with one critical flaw. (significa...,NaN,NaN,Gregory P. Baker
14728,AVpff7_VilAPnD_xc1E_,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B00DU15MU4,Amazon,"Electronics,Categories,Streaming Media Players...","848719035551,0848719035551,certifiedrefurbishe...",Amazon,2014-04-07T00:00:00Z,NaN,2016-03-10T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Certified-Refurbished-Am...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,059 people found...",NaN,NaN,Mandy
14729,AVpff7_VilAPnD_xc1E_,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B00DU15MU4,Amazon,"Electronics,Categories,Streaming Media Players...","848719035551,0848719035551,certifiedrefurbishe...",Amazon,2014-04-06T00:00:00Z,NaN,2016-03-08T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Certified-Refurbished-Am...,An Amazon.com official commented on this revie...,"I like it Amazon...But this is IMPORTANT 5,859...",NaN,NaN,Dallas
14731,AVpff7_VilAPnD_xc1E_,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B00DU15MU4,Amazon,"Electronics,Categories,Streaming Media Players...","848719035551,0848719035551,certifiedrefurbishe...",Amazon,2014-04-03T00:00:00Z,NaN,2015-09-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Certified-Refurbished-Am...,"Having received my Fire TV today, I've been tr...",Works great with one critical flaw. (significa...,NaN,NaN,Gregory P. Baker
14732,AVpff7_VilAPnD_xc1E_,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B00DU15MU4,Amazon,"Electronics,Categories,Streaming Media Players...","848719035551,0848719035551,certifiedrefurbishe...",Amazon,NaN,NaN,2015-09-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Certified-Refurbished-Am...,I am not a casual user of on-demand content an...,This box is a GAME CHANGER for on demand conte...,NaN,NaN,William Hardin
21226,AVpe7AsMilAPnD_xQ78G,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B00QJDU3KY,Amazon,"mazon.co.uk,Amazon Devices",kindlepaperwhite/b00qjdu3ky,Amazon,2015-07-08T00:00:00Z,NaN,2016-03-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Paperwhite-High-R...,"My previous kindle was a DX, this is my second...",Great device for reading. 8 people found this ...,NaN,NaN,Kelvin Law
21227,AVpe7AsMilAPnD_xQ78G,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B00QJDU3KY,Amazon,"mazon.co.uk,Amazon Devices",kindlepaperwhite/b00qjdu3ky,Amazon,2015-07-03T00:00:00Z,NaN,2016-03-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Paperwhite-High-R...,Just got mine right now. Looks the same as the...,Definitely better than the previous generation...,NaN,NaN,Bandler
21228,AVpe7AsMilAPnD_xQ78G,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B00QJDU3KY,Amazon,"mazon.co.uk,Amazon Devices",kindlepaperwhite/b00qjdu3ky,Amazon,2015-07-01T00:00:00Z,NaN,2016-03-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Paperwhite-High-R...,As reviewed by the wife This is the perfect th...,Give this to a book-loving-new-mommy-who-breas...,NaN,NaN,Miguel Martinez
21229,AVpe7AsMilAPnD_xQ78G,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B00QJDU3KY,Amazon,"mazon.co.uk,Amazon Devices",kindlepaperwhite/b00qjdu3ky,Amazon,2015-08-05T00:00:00Z,NaN,2016-03-13T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Kindle-Paperwhite-High-R...,My new Kindle Paperwhite came from the USA to ...,"Trouble-free international shipping, and easy ...",NaN,NaN,Magnus Brattemark
29572,AVpe8PEVilAPnD_xRYIi,NaN,B00BFJAHF8,Amazon Coco T,"Rice Dishes,Ready Meals,Beauty,Moisturizers,Lo...","amazoncocot/spk73188,coconutwaterredtea165ozpa...",Amazon,NaN,NaN,2016-02-01T00:00:00Z,...,NaN,NaN,NaN,NaN,http://www.amazon.com/Coconut-Water-Red-16-5--...,This stuff tastes great. It does have sugar in...,Five Stars,NaN,NaN,Caroline Dick

In [10]:
# Create a new DataFrame containing only rows
# that have both review text and a star rating.
df_sentiment = df.dropna(
    subset=["reviews.text", "reviews.rating"]
)

# Check the new number of rows and columns.
df_sentiment.shape

(34626, 21)

## 6. Investigating duplicate reviews

A duplicate review means the same review text appears more than once.

Duplicates can affect model training because repeated examples may receive too much importance.

Before removing duplicates, we will:
- count repeated review texts
- inspect examples
- decide whether they are true duplicates

In [11]:
# Count how many review texts are duplicates.
df_sentiment["reviews.text"].duplicated().sum()

np.int64(0)

In [12]:
# Show rows where the same review text appears more than once.
duplicate_reviews = df_sentiment[
    df_sentiment["reviews.text"].duplicated(keep=False)
]

# Display useful columns from the duplicated reviews.
duplicate_reviews[
    ["name", "reviews.rating", "reviews.text"]
].head(20)

Empty DataFrame
Columns: [name, reviews.rating, reviews.text]
Index: []

### Finding

No duplicated review texts were found in the cleaned sentiment dataset.

Therefore, we do not need to remove duplicate reviews at this stage.

## 7. Inspecting rating distribution

The rating distribution shows how many reviews have 1, 2, 3, 4, or 5 stars.

This matters because we will later convert ratings into sentiment classes:
- 1–2 → Negative
- 3 → Neutral
- 4–5 → Positive

If one group is much larger than the others, the dataset may be imbalanced.

In [13]:
# Select only the rating column.
ratings = df_sentiment["reviews.rating"]

# Count each different rating.
rating_counts = ratings.value_counts()

# Sort the result by rating value.
rating_counts = rating_counts.sort_index()

# Display the result.
rating_counts

reviews.rating
1.0      410
2.0      402
3.0     1499
4.0     8541
5.0    23774
Name: count, dtype: int64

In [ ]:
# df_sentiment["reviews.rating"].value_counts().sort_index()

# This is called method chaining: one operation produces a result, and the next operation acts on that result.

In [16]:
# Example rating value to test our logic.
rating = 5

# Check whether the rating is 1 or 2.
if rating == 1 or rating == 2:
    print("Negative")

# If the first condition was false, check whether the rating is 3.
elif rating == 3:
    print("Neutral")

# If none of the previous conditions were true, it must be 4 or 5.
else:
    print("Positive")

Positive

In [ ]:
## 8. Normalizing review text

Some reviews may look identical to a person but differ because of:
- extra spaces
- line breaks
- tabs

We will normalize whitespace before checking duplicates again.

In [17]:
# Create a cleaned version of the review text.
# .str converts the column into Pandas string operations.
# .replace() changes repeated whitespace into a single space.
# .strip() removes spaces at the beginning and end.

df_sentiment["reviews.text"] = (
    df_sentiment["reviews.text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [18]:
# Count duplicated review texts after whitespace normalization.
duplicate_count = df_sentiment["reviews.text"].duplicated().sum()

duplicate_count

np.int64(11)

In [19]:
# Show all duplicated review texts after normalization.
duplicate_reviews = df_sentiment[
    df_sentiment["reviews.text"].duplicated(keep=False)
]

duplicate_reviews[
    ["name", "reviews.rating", "reviews.text"]
]

,name,reviews.rating,reviews.text
869,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",2.0,This tablet could be so much better if the app...
1693,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",4.0,Needed an inexpensive and portable Alexa devic...
2619,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",5.0,I needed a tablet to keep at the hospital duri...
5357,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,I used a couple of the brands that are just pr...
5750,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,Easy to navigatePerfect for little ones Buy a ...
13323,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,Great product and only $40! I purchased 2 of t...
15438,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,2.0,Amazon fire is a good tablet if you like e-boo...
15770,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",2.0,Amazon fire is a good tablet if you like e-boo...
17667,Amazon Kindle Paperwhite - eBook reader - 4 GB...,4.0,Purchased this as an upgrade to the first gene...
19978,Amazon Kindle Paperwhite - eBook reader - 4 GB...,4.0,"If you like to read books, I totally recommend..."
20427,"Kindle Voyage E-reader, 6 High-Resolution Disp...",4.0,Bought this for my son to encourage his readin...
21272,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,Purchased this as an upgrade to the first gene...
21274,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,Bought this for my son to encourage his readin...
21275,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,"If you like to read books, I totally recommend..."
21292,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",2.0,This tablet could be so much better if the app...
21293,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,I needed a tablet to keep at the hospital duri...
21549,"Echo (White),,,\r\nEcho (White),,,",4.0,Needed an inexpensive and portable Alexa devic...
21588,"Echo (White),,,\r\nEcho (White),,,",5.0,I used a couple of the brands that are just pr...
21869,"Echo (White),,,\r\nEcho (White),,,",5.0,Easy to navigatePerfect for little ones Buy a ...
21870,"Echo (White),,,\r\nEcho (White),,,",5.0,Great product and only $40! I purchased 2 of t...
28726,NaN,5.0,This was an Xmas gift for my wife. She had wan...
28935,NaN,5.0,This was an Xmas gift for my wife. She had wan...

In [20]:
# Sort duplicated reviews alphabetically by their text.
# This makes matching duplicate rows easier to compare.

duplicate_reviews_sorted = duplicate_reviews.sort_values("reviews.text")

# Display the text and rating together.
duplicate_reviews_sorted[
    ["reviews.text", "reviews.rating", "name"]
]

,reviews.text,reviews.rating,name
15438,Amazon fire is a good tablet if you like e-boo...,2.0,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...
15770,Amazon fire is a good tablet if you like e-boo...,2.0,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16..."
20427,Bought this for my son to encourage his readin...,4.0,"Kindle Voyage E-reader, 6 High-Resolution Disp..."
21274,Bought this for my son to encourage his readin...,4.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
21869,Easy to navigatePerfect for little ones Buy a ...,5.0,"Echo (White),,,\r\nEcho (White),,,"
5750,Easy to navigatePerfect for little ones Buy a ...,5.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
13323,Great product and only $40! I purchased 2 of t...,5.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
21870,Great product and only $40! I purchased 2 of t...,5.0,"Echo (White),,,\r\nEcho (White),,,"
21293,I needed a tablet to keep at the hospital duri...,5.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
2619,I needed a tablet to keep at the hospital duri...,5.0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,..."
21588,I used a couple of the brands that are just pr...,5.0,"Echo (White),,,\r\nEcho (White),,,"
5357,I used a couple of the brands that are just pr...,5.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
21275,"If you like to read books, I totally recommend...",4.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
19978,"If you like to read books, I totally recommend...",4.0,Amazon Kindle Paperwhite - eBook reader - 4 GB...
21549,Needed an inexpensive and portable Alexa devic...,4.0,"Echo (White),,,\r\nEcho (White),,,"
1693,Needed an inexpensive and portable Alexa devic...,4.0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,..."
21272,Purchased this as an upgrade to the first gene...,4.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
17667,Purchased this as an upgrade to the first gene...,4.0,Amazon Kindle Paperwhite - eBook reader - 4 GB...
869,This tablet could be so much better if the app...,2.0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,..."
21292,This tablet could be so much better if the app...,2.0,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
28726,This was an Xmas gift for my wife. She had wan...,5.0,NaN
28935,This was an Xmas gift for my wife. She had wan...,5.0,NaN

In [21]:
# Group rows that have exactly the same review text.
duplicate_rating_check = (
    duplicate_reviews
    .groupby("reviews.text")["reviews.rating"]
    .nunique()
)

# Show only review texts that have more than one different rating.
conflicting_duplicates = duplicate_rating_check[
    duplicate_rating_check > 1
]

conflicting_duplicates

Series([], Name: reviews.rating, dtype: int64)

In [22]:
# Remove duplicated review texts.
# keep="first" means we keep the first occurrence
# and remove later repetitions.

df_sentiment = df_sentiment.drop_duplicates(
    subset=["reviews.text"],
    keep="first"
)

# Check the final shape.
df_sentiment.shape

(34615, 21)

In [23]:
# Confirm there are no duplicated review texts left.
df_sentiment["reviews.text"].duplicated().sum()

np.int64(0)

Why we do not split yet
The model will eventually learn this relationship:
reviews.text  →  sentiment

But right now you still only have:
reviews.text
reviews.rating

So first we transform the rating into the target we actually want to predict:
1–2 → negative
3   → neutral
4–5 → positive

Then we will have:
INPUT (X)               TARGET (y)

"This is terrible"   →  negative
"It's okay"          →  neutral
"I love it"          →  positive

After that, splitting makes sense.

## 9. Creating sentiment labels

### Question

How can we convert the star rating into the category that we actually want the model to predict?

### Rule

- 1–2 stars → Negative
- 3 stars → Neutral
- 4–5 stars → Positive

In [27]:
# Create a function that receives one star rating
# and returns the corresponding sentiment label.
def get_sentiment(rating):

    # Ratings 1 and 2 represent negative reviews.
    if rating == 1 or rating == 2:
        return "negative"

    # Rating 3 represents a neutral review.
    elif rating == 3:
        return "neutral"

    # Ratings 4 and 5 represent positive reviews.
    else:
        return "positive"
    
    # Test the function manually before applying it to the dataset.
print(get_sentiment(1))
print(get_sentiment(3))
print(get_sentiment(5))

negative
neutral
positive

In [30]:
sentiment_labels = df_sentiment["reviews.rating"].apply(get_sentiment)

In [31]:
# Save the generated sentiment labels in a new column.
df_sentiment["sentiment"] = sentiment_labels

In [32]:
# Show the rating and the new sentiment label side by side.
df_sentiment[
    ["reviews.rating", "sentiment"]
].head(10)

   reviews.rating sentiment
0             5.0  positive
1             5.0  positive
2             5.0  positive
3             4.0  positive
4             5.0  positive
5             5.0  positive
6             4.0  positive
7             5.0  positive
8             5.0  positive
9             5.0  positive

In [33]:
# Select the sentiment column.
sentiments = df_sentiment["sentiment"]

# Count how many examples exist in each sentiment class.
sentiment_counts = sentiments.value_counts()

# Display the results
sentiment_counts

sentiment
positive    32306
neutral      1499
negative      810
Name: count, dtype: int64

## 11. Preparing the data for model training

### Question

Which information will the model use as input, and what are we asking it to predict?

For sentiment analysis:

- `reviews.text` = input text
- `sentiment` = target label

In machine learning, these are commonly called:

- `X` = features / input
- `y` = target / answer

X
"This tablet is excellent"
            ↓
          MODEL
            ↓
y
"positive"

so split the dat is orgnaze the data so the models knows what is feature and what is the target

In [34]:
# Select the review text that the model will use as input.

X = df_sentiment["reviews.text"]

# Select the sentiment label that the model will learn to predict.

Y = df_sentiment["sentiment"]

In [35]:
# Display the first 5 review texts.
X.head()

0    This product so far has not disappointed. My c...
1    great for beginner or experienced person. Boug...
2    Inexpensive tablet for him to use and learn on...
3    I've had my Fire HD 8 two weeks now and I love...
4    I bought this for my grand daughter when she c...
Name: reviews.text, dtype: str

In [38]:
Y.head()

0    positive
1    positive
2    positive
3    positive
4    positive
Name: sentiment, dtype: str

If we train a model on all 34,615 reviews, how could we know whether it works on reviews it has never seen?

We cannot.

So we divide the dataset:

ALL DATA
   ↓
┌───────────────┬───────────────┐
│ TRAINING DATA │   TEST DATA   │
│     ~80%      │     ~20%      │
└───────────────┴───────────────┘

The training set is what the model learns from.
The test set stays hidden until evaluation.

training = studying exercises
test     = final exam

If the model sees the test answers during training, the evaluation becomes unreliable.
## That is called data leakage.

In [39]:
# Import the function used to divide data into training and test sets.
from sklearn.model_selection import train_test_split

In [42]:
# Split the data into training and test sets.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42,
    stratify=Y
)

random_state=42

makes the random split reproducible.
That means you, Diogo, and your instructor can run the same code and get the same split.
42 itself is not special. It is just a commonly used fixed number.
stratify=y
This one is particularly important for your dataset.

positive ≈ 93%
neutral  ≈ 4%
negative ≈ 2%

stratify=y tells scikit-learn:
Keep approximately the same sentiment proportions in both the training and test sets.

In [43]:
len(X_train)

27692

In [44]:
len(X_test)

6923

## 12. Verifying the train/test split

### Question

Did the train/test split preserve approximately the same proportion of Positive, Neutral, and Negative reviews?

Because the dataset is highly imbalanced, we used `stratify=y` to keep similar class proportions in both sets.

In [48]:
# Count the sentiment classes in the training set.
train_class_counts = y_train.value_counts()

# Display the result.
train_class_counts

sentiment
positive    25845
neutral      1199
negative      648
Name: count, dtype: int64

In [47]:
# Count the sentiment classes in the test set.
test_class_counts = y_test.value_counts()

# Display the result.
test_class_counts

sentiment
positive    6461
neutral      300
negative     162
Name: count, dtype: int64

In [49]:
# Calculate the percentage of each sentiment class
# in the training set.
train_class_percentages = (
    train_class_counts / len(y_train)
) * 100

train_class_percentages

sentiment
positive    93.330204
neutral      4.329770
negative     2.340026
Name: count, dtype: float64

In [50]:
# Calculate the percentage of each sentiment class
# in the test set.
test_class_percentages = (
    test_class_counts / len(y_test)
) * 100

test_class_percentages

sentiment
positive    93.326593
neutral      4.333381
negative     2.340026
Name: count, dtype: float64

### Finding

The train/test split preserved almost exactly the same sentiment distribution in both datasets.

Training set:
- Positive: ~93.33%
- Neutral: ~4.33%
- Negative: ~2.34%

Test set:
- Positive: ~93.33%
- Neutral: ~4.33%
- Negative: ~2.34%

This confirms that `stratify=y` worked correctly.

## 13. Converting text into numbers with TF-IDF

### Question

How can a machine-learning model work with text?

Models such as Logistic Regression cannot directly understand words.

TF-IDF converts review text into numerical features that a model can process.

TF-IDF gives more importance to words that are useful for distinguishing documents and less importance to words that appear everywhere.

For the training set, TF-IDF will:
1. learn the vocabulary from `X_train`
2. calculate the TF-IDF weights
3. convert each review into numerical features

For the test set, we will only transform the text using what was learned from the training set.


X_train / X_test
      ↓
TF-IDF
      ↓
X_train_tfidf / X_test_tfidf
      ↓
Logistic Regression
      ↓
predictions
      ↓
accuracy
precision
recall
F1-score
confusion matrix

MVP with 3 baseline models, after Logistic Regression we will do something like:
Model 1: Logistic Regression
Model 2: Linear SVM
Model 3: Naive Bayes

All three will use the same train/test split so the comparison is fair.

In [ ]:
# 1. Convert text into numbers with TF-IDF

# Import the TF-IDF vectorizer from scikit-learn.
from sklearn.feature_extraction.text import TfidfVectorizer

# sklearn → the machine learning library
# feature_extraction → tools for creating useful model inputs
# text → specifically text-related tools
# TfidfVectorizer → the tool we want

In [71]:
# Create the TF-IDF vectorizer using the same settings as Diogo.
tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2)
)

In [72]:
# Learn the vocabulary from the training reviews
# and convert the training text into numerical features.
X_train_tfidf = tfidf.fit_transform(X_train)

fit
→ learn from the training text

transform
→ convert the text into numbers

In [74]:
# Convert the test reviews into numerical features
# using only the vocabulary learned from the training set.
X_test_tfidf = tfidf.transform(X_test)

In [75]:
# Check the size of the transformed training data.
X_train_tfidf.shape

(27692, 10000)

In [76]:
# Check the size of the transformed test data.
X_test_tfidf.shape

(6923, 10000)

## 14. Baseline Model 1 — Logistic Regression

### Why are we using Logistic Regression?

Logistic Regression is a classification algorithm.

In this project, we want to classify each review as:
- Negative
- Neutral
- Positive

We are starting with Logistic Regression because it is:
- simple to train
- fast
- commonly used with TF-IDF text features
- a useful baseline for comparing other models

A baseline is our first reference model. Later, we will compare its results with SVM and Naive Bayes.

### Question

Can Logistic Regression learn useful sentiment patterns from the TF-IDF features?

In [77]:
# Import the Logistic Regression classifier.
from sklearn.linear_model import LogisticRegression

In [78]:
# Create the Logistic Regression model.
logistic_model = LogisticRegression(
    max_iter=1000
)

In [80]:
# Train the model using the TF-IDF training features
# and the correct sentiment labels.
logistic_model.fit(
    X_train_tfidf,
    y_train
)

LogisticRegression(max_iter=1000)

X_train_tfidf
= numerical information from the review text

y_train
= the correct sentiment answers

The most important parts are:
- classes_ = ['negative', 'neutral', 'positive']
  The model knows there are 3 sentiment classes.
- n_features_in_ = 12589
  It received the 12,589 TF-IDF features we created earlier.
- n_iter_ = [44]
  It converged in 44 iterations, so max_iter=1000 was more than enough.
- coef_
  These are the learned weights for the TF-IDF features. You do not need to interpret all of those now.

In [81]:
# Predict the sentiment of the unseen test reviews.
logistic_predictions = logistic_model.predict(
    X_test_tfidf
)

In [82]:
# Show the first 10 predictions made by the model.
logistic_predictions[:10]

array(['positive', 'positive', 'positive', 'positive', 'positive',
       'positive', 'positive', 'positive', 'positive', 'positive'],
      dtype=object)

In [83]:
# Show the first 10 correct sentiment labels.
y_test.iloc[:10]

33134    positive
25411    positive
33441    positive
22489    positive
12639    positive
27721    positive
5606     positive
32750    positive
14621     neutral
13322    positive
Name: sentiment, dtype: str

In [ ]:
## 15. Evaluating Logistic Regression

### Question

How well does the model perform on unseen reviews?

We will evaluate it using:

- Accuracy
- Precision
- Recall
- F1-score
- Confusion Matrix

Because the dataset is highly imbalanced, accuracy alone may be misleading.

In [67]:
# Import evaluation metrics from scikit-learn.
from sklearn.metrics import(
    accuracy_score,
    classification_report,
    confusion_matrix
)

accuracy_score
→ overall percentage of correct predictions

classification_report
→ precision, recall, and F1-score for each class

confusion_matrix
→ shows which classes the model confuses with each other

In [86]:
# Calculate the proportion of correct predictions.
logistic_accuracy = accuracy_score(
    y_test,
    logistic_predictions
)

# Display the accuracy.
logistic_accuracy

0.9362992922143579

In [87]:
# Show precision, recall, and F1-score
# for Negative, Neutral, and Positive classes.
logistic_report = classification_report(
    y_test,
    logistic_predictions
)

print(logistic_report)

              precision    recall  f1-score   support

    negative       0.62      0.15      0.25       162
     neutral       0.50      0.05      0.09       300
    positive       0.94      1.00      0.97      6461

    accuracy                           0.94      6923
   macro avg       0.69      0.40      0.43      6923
weighted avg       0.91      0.94      0.91      6923

In [85]:
# Create a confusion matrix.
logistic_confusion_matrix = confusion_matrix(
    y_test,
    logistic_predictions
)

logistic_confusion_matrix

array([[  25,    6,  131],
       [   5,   14,  281],
       [  10,    8, 6443]])

negative
precision = 0.60
recall    = 0.15
F1        = 0.24

neutral
precision = 0.42
recall    = 0.06
F1        = 0.10

positive
precision = 0.94
recall    = 1.00
F1        = 0.97

precision
= when the model predicts this class, how often is it right?

recall
= of all real examples of this class, how many did the model actually find?

F1
= balance between precision and recall

In [ ]:
### Finding

Logistic Regression achieved approximately 93.6% accuracy.

However, this result is misleading because the dataset is highly imbalanced.

The model performs very well on the Positive class, but poorly on the minority classes:

- Negative recall: 0.15
- Neutral recall: 0.06
- Positive recall: 1.00

This suggests the model is strongly biased toward predicting Positive reviews.

Therefore, accuracy alone is not a sufficient metric for this problem.

## 16. Baseline Model 2 — Naive Bayes

### Why are we using Naive Bayes?

Naive Bayes is a classification algorithm commonly used for text problems.

It estimates which sentiment class is most probable based on the features found in a review.

It is:
- fast
- simple
- commonly used as a text-classification baseline
- useful to compare against Logistic Regression and Linear SVM

### Question

Can Naive Bayes classify sentiment effectively using the same TF-IDF features?

In [88]:
# Import Multinomial Naive Bayes.
from sklearn.naive_bayes import MultinomialNB

In [89]:
# Create the Naive Bayes model.
naive_bayes_model = MultinomialNB()

In [90]:
# Train Naive Bayes using the same TF-IDF training data.
naive_bayes_model.fit(
    X_train_tfidf,
    y_train
)

MultinomialNB()

In [91]:
# Predict sentiment for the unseen test reviews.
naive_bayes_predictions = naive_bayes_model.predict(
    X_test_tfidf
)

In [92]:
# Calculate Naive Bayes accuracy.
naive_bayes_accuracy = accuracy_score(
    y_test,
    naive_bayes_predictions
)

naive_bayes_accuracy

0.9332659251769464

In [93]:
# Generate precision, recall, and F1-score.
naive_bayes_report = classification_report(
    y_test,
    naive_bayes_predictions
)

print(naive_bayes_report)

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00       162
     neutral       0.00      0.00      0.00       300
    positive       0.93      1.00      0.97      6461

    accuracy                           0.93      6923
   macro avg       0.31      0.33      0.32      6923
weighted avg       0.87      0.93      0.90      6923

/Users/caiomaia/ironhack-workspace/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/caiomaia/ironhack-workspace/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/caiomaia/ironhack-workspace/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [94]:
# Generate the confusion matrix.
naive_bayes_confusion_matrix = confusion_matrix(
    y_test,
    naive_bayes_predictions
)

naive_bayes_confusion_matrix

array([[   0,    1,  161],
       [   0,    0,  300],
       [   0,    0, 6461]])

In [ ]:
## 17. Baseline model comparison

We compared three classifiers using the same:
- cleaned dataset
- train/test split
- TF-IDF configuration
- evaluation metrics

| Model | Accuracy | Macro F1 | Negative F1 | Neutral F1 | Positive F1 |
|---|---:|---:|---:|---:|---:|
| Logistic Regression | 0.936 | 0.43 | 0.25 | 0.09 | 0.97 |
| Linear SVM | 0.935 | 0.49 | 0.32 | 0.17 | 0.97 |
| Naive Bayes | 0.933 | 0.32 | 0.00 | 0.00 | 0.97 |

### Finding

Accuracy alone is misleading because the dataset is highly imbalanced toward Positive reviews.

Linear SVM achieved the strongest balanced performance among the three baseline models, especially on the minority classes.